apiVersion: v1
kind: Pod

metadata:
  name: expense-resource

spec:
  containers:
    - name: nginx
      image: nginx

      resources:
        requests:
          cpu: "250M"
          #millicpu
          memory: "64MI"
          #mebibytes

        limits:
          cpu: "1000M"
          memory: "128MI"


