apiVersion: v1
kind: Pod

metadata:
  name: expense-resource

spec:
  containers:
    - name: nginx
      image: nginx

      resources:
        requests:
          memory: "64Mi"
          #mebibytes
          cpu: "250m"
          #millicpu
          

        limits:
          memory: "128Mi"
          cpu: "1000m"



apiVersion: v1
kind: Pod
metadata:
  name: expense

spec: 
  containers:
    - name: nginx
      image: nginx

      resources:
        requests: 
          memory:
          cpu:

        limits: 
          memory:
          cpu: 
          


