apiVersion: v1
kind: ConfigMap

metadata:
  name: configuration-expense



data:
  name: project
  value: Retail

  # key-valu pair
# when we do changes in configmap,pod gets deleted and will recreate..